Simple Rails/config/routes.rb
Rails.application.routes.draw do
  resources :test_classes
  resources :my_classes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Simple Rails/app/models/my_class.rb
class MyClass < ApplicationRecord
end

Simple Rails/app/models/test_class.rb
class TestClass < ApplicationRecord
end

Simple Rails/app/controllers/my_classes_controller.rb
class MyClassesController < ApplicationController
  before_action :set_my_class, only: [:show, :edit, :update, :destroy]

  # GET /my_classes
  # GET /my_classes.json
  def index
    @my_classes = MyClass.all
  end

  # GET /my_classes/1
  # GET /my_classes/1.json
  def show
  end

  # GET /my_classes/new
  def new
    @my_class = MyClass.new
  end

  # GET /my_classes/1/edit
  def edit
  end

  # POST /my_classes
  # POST /my_classes.json
  def create
    @my_class = MyClass.new(my_class_params)

    respond_to do |format|
      if @my_class.save
        format.html { redirect_to @my_class, notice: 'My class was successfully created.' }
        format.json { render :show, status: :created, location: @my_class }
      else
        format.html { render :new }
        format.json { render json: @my_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_classes/1
  # PATCH/PUT /my_classes/1.json
  def update
    respond_to do |format|
      if @my_class.update(my_class_params)
        format.html { redirect_to @my_class, notice: 'My class was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_class }
      else
        format.html { render :edit }
        format.json { render json: @my_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_classes/1
  # DELETE /my_classes/1.json
  def destroy
    @my_class.destroy
    respond_to do |format|
      format.html { redirect_to my_classes_url, notice: 'My class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_class
      @my_class = MyClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_class_params
      params.require(:my_class).permit(:name, :content)
    end
end

Simple Rails/app/controllers/test_classes_controller.rb
class TestClassesController < ApplicationController
  before_action :set_test_class, only: [:show, :edit, :update, :destroy]

  # GET /test_classes
  # GET /test_classes.json
  def index
    @test_classes = TestClass.all
  end

  # GET /test_classes/1
  # GET /test_classes/1.json
  def show
  end

  # GET /test_classes/new
  def new
    @test_class = TestClass.new
  end

  # GET /test_classes/1/edit
  def edit
  end

  # POST /test_classes
  # POST /test_classes.json
  def create
    @test_class = TestClass.new(test_class_params)

    respond_to do |format|
      if @test_class.save
        format.html { redirect_to @test_class, notice: 'Test class was successfully created.' }
        format.json { render :show, status: :created, location: @test_class }
      else
        format.html { render :new }
        format.json { render json: @test_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_classes/1
  # PATCH/PUT /test_classes/1.json
  def update
    respond_to do |format|
      if @test_class.update(test_class_params)
        format.html { redirect_to @test_class, notice: 'Test class was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_class }
      else
        format.html { render :edit }
        format.json { render json: @test_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_classes/1
  # DELETE /test_classes/1.json
  def destroy
    @test_class.destroy
    respond_to do |format|
      format.html { redirect_to test_classes_url, notice: 'Test class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_class
      @test_class = TestClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_class_params
      params.require(:test_class).permit(:startDate, :myBool, :myFloat)
    end
end

Simple Rails/app/helpers/my_classes_helper.rb
module MyClassesHelper
end

Simple Rails/app/helpers/test_classes_helper.rb
module TestClassesHelper
end

Simple Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Simple Rails/app/views/my_classes/_form.html.erb
<%= form_with(model: my_class, local: true) do |form| %>
  <% if my_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_class.errors.count, "error") %> prohibited this my_class from being saved:</h2>

      <ul>
        <% my_class.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Simple Rails/app/views/my_classes/edit.html.erb
<h1>Editing My Class</h1>

<%= render 'form', my_class: @my_class %>

<%= link_to 'Show', @my_class %> |
<%= link_to 'Back', my_classes_path %>

Simple Rails/app/views/my_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_classes.each do |my_class| %>
      <tr>
        <td><%= my_class.name %></td>
        <td><%= my_class.content %></td>
        <td><%= link_to 'Show', my_class %></td>
        <td><%= link_to 'Edit', edit_my_class_path(my_class) %></td>
        <td><%= link_to 'Destroy', my_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Class', new_my_class_path %>

Simple Rails/app/views/my_classes/new.html.erb
<h1>New My Class</h1>

<%= render 'form', my_class: @my_class %>

<%= link_to 'Back', my_classes_path %>

Simple Rails/app/views/my_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @my_class.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @my_class.content %>
</p>

<%= link_to 'Edit', edit_my_class_path(@my_class) %> |
<%= link_to 'Back', my_classes_path %>

Simple Rails/app/views/test_classes/_form.html.erb
<%= form_with(model: test_class, local: true) do |form| %>
  <% if test_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_class.errors.count, "error") %> prohibited this test_class from being saved:</h2>

      <ul>
        <% test_class.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :startDate %>
    <%= form.datetime_select :startDate %>
  </div>

  <div class="field">
    <%= form.label :myBool %>
    <%= form.check_box :myBool %>
  </div>

  <div class="field">
    <%= form.label :myFloat %>
    <%= form.text_field :myFloat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Simple Rails/app/views/test_classes/edit.html.erb
<h1>Editing Test Class</h1>

<%= render 'form', test_class: @test_class %>

<%= link_to 'Show', @test_class %> |
<%= link_to 'Back', test_classes_path %>

Simple Rails/app/views/test_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Classes</h1>

<table>
  <thead>
    <tr>
      <th>Startdate</th>
      <th>Mybool</th>
      <th>Myfloat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_classes.each do |test_class| %>
      <tr>
        <td><%= test_class.startDate %></td>
        <td><%= test_class.myBool %></td>
        <td><%= test_class.myFloat %></td>
        <td><%= link_to 'Show', test_class %></td>
        <td><%= link_to 'Edit', edit_test_class_path(test_class) %></td>
        <td><%= link_to 'Destroy', test_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test Class', new_test_class_path %>

Simple Rails/app/views/test_classes/new.html.erb
<h1>New Test Class</h1>

<%= render 'form', test_class: @test_class %>

<%= link_to 'Back', test_classes_path %>

Simple Rails/app/views/test_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Startdate:</strong>
  <%= @test_class.startDate %>
</p>

<p>
  <strong>Mybool:</strong>
  <%= @test_class.myBool %>
</p>

<p>
  <strong>Myfloat:</strong>
  <%= @test_class.myFloat %>
</p>

<%= link_to 'Edit', edit_test_class_path(@test_class) %> |
<%= link_to 'Back', test_classes_path %>